### ISSUE TITLE
Server Crash while Migration

### ISSUE THREAD

**Issue by suerion** [CortexPE/Hierarchy#28]
After Restart with the new Update, it would Migrate some Roles, but ther is the next problem. Here is the Crashdump

```
THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: Hierarchy v1.2.0

Code:
[130] 
[131] 	/**
[132] 	 * @param int $roleID
[133] 	 *
[134] 	 * @return int
[135] 	 * @throws UnresolvedRoleException
[136] 	 */
[137] 	private function resolveRoleIndex(int $roleID): int {
[138] 		foreach($this->roles as $i => $role) {
[139] 			if($role["ID"] == $roleID) {
[140] 				return $i;
[141] 			}
[142] 		}
[143] 		throw new UnresolvedRoleException("Unable to resolve unknown role with ID {$roleID}");
[144] 	}
[145] 
[146] 	public function shutdown(): void {
[147] 		// should be saved already
[148] 	}
[149] 

Backtrace:
#0 plugins/Hierarchy_dev-85.phar/src/CortexPE/Hierarchy/data/role/IndexedRoleDS(139): pocketmine\utils\Utils::errorExceptionHandler(integer 2, string[26] Illegal string offset 'ID', string[136] phar:///home/minecraft/multicraft/servers/PE/pocketmine/plugins/Hierarchy_dev-85, integer 139, array[3])
#1 plugins/Hierarchy_dev-85.phar/src/CortexPE/Hierarchy/data/role/IndexedRoleDS(110): CortexPE\Hierarchy\data\role\IndexedRoleDS->resolveRoleIndex(integer 4)
#2 plugins/Hierarchy_dev-85.phar/src/CortexPE/Hierarchy/data/role/IndexedRoleDS(96): CortexPE\Hierarchy\data\role\IndexedRoleDS->removeRolePermission(object CortexPE\Hierarchy\role\Role, string[20] pocketmine.broadcast)
#3 plugins/Hierarchy_dev-85.phar/src/CortexPE/Hierarchy/role/Role(164): CortexPE\Hierarchy\data\role\IndexedRoleDS->addRolePermission(object CortexPE\Hierarchy\role\Role, object pocketmine\permission\Permission, boolean 1)
#4 plugins/HRKMigrator_dev-3.phar/src/CortexPE/HRKMigrator/Main(245): CortexPE\Hierarchy\role\Role->denyPermission(object pocketmine\permission\Permission)
#5 plugins/HRKMigrator_dev-3.phar/src/CortexPE/HRKMigrator/Main(134): CortexPE\HRKMigrator\Main::procRolePermission(object CortexPE\Hierarchy\role\Role, string[20] pocketmine.broadcast)
#6 plugins/HRKMigrator_dev-3.phar/src/CortexPE/HRKMigrator/Main(81): CortexPE\HRKMigrator\Main->doMigration()
#7 src/pocketmine/scheduler/ClosureTask(61): CortexPE\HRKMigrator\Main->CortexPE\HRKMigrator\{closure}(integer 1)
#8 src/pocketmine/scheduler/TaskHandler(134): pocketmine\scheduler\ClosureTask->onRun(integer 1)
#9 src/pocketmine/scheduler/TaskScheduler(176): pocketmine\scheduler\TaskHandler->run(integer 1)
#10 src/pocketmine/plugin/PluginManager(643): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(integer 1)
#11 src/pocketmine/Server(2380): pocketmine\plugin\PluginManager->tickSchedulers(integer 1)
#12 src/pocketmine/Server(2143): pocketmine\Server->tick()
#13 src/pocketmine/Server(1990): pocketmine\Server->tickProcessor()
#14 src/pocketmine/Server(1584): pocketmine\Server->start()
#15 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[49] /home/minecraft/multicraft/servers/PE/pocketmine/, string[57] /home/minecraft/multicraft/servers/PE/pocketmine/plugins/)
#16 src/pocketmine/PocketMine(296): pocketmine\server()
#17 (11): require(string[104] phar:///home/minecraft/multicraft/servers/PE/pocketmine/PocketMine-MP.phar/src/p)
```

**Comment by suerion** [comment]
this merge fix will not fix my failure after migrating,

Extract with dev Tools, edited the file how it should be in the merge of intagaming -> created a new phar -> same issue

```
[19:35:52] [Server thread/INFO]: [HRKMigrator] Loading PurePerms group data...
[19:35:52] [Server thread/INFO]: [HRKMigrator] Migrating 'Kinder' group permissions...
[19:35:52] [Server thread/INFO]: [HRKMigrator] Migrating 'Eltern' group permissions...
[19:35:52] [Server thread/INFO]: [HRKMigrator] Migrating 'Architekten' group permissions...
[19:35:52] [Server thread/CRITICAL]: ErrorException: "Illegal string offset 'ID'" (EXCEPTION) in "plugins/Hierarchy_v1.2.0.phar/src/CortexPE/Hierarchy/data/role/IndexedRoleDS" at line 139
[19:35:52] [Server thread/DEBUG]: #0 plugins/Hierarchy_v1.2.0.phar/src/CortexPE/Hierarchy/data/role/IndexedRoleDS(139): pocketmine\utils\Utils::errorExceptionHandler(integer 2, string[26] Illegal string offset 'ID', string[136] phar:///home/minecraft/multicraft/servers/PE/pocketmine/plugins/Hierarchy_v1.2.0, integer 139, array[3])
[19:35:52] [Server thread/DEBUG]: #1 plugins/Hierarchy_v1.2.0.phar/src/CortexPE/Hierarchy/data/role/IndexedRoleDS(110): CortexPE\Hierarchy\data\role\IndexedRoleDS->resolveRoleIndex(integer 4)
[19:35:52] [Server thread/DEBUG]: #2 plugins/Hierarchy_v1.2.0.phar/src/CortexPE/Hierarchy/data/role/IndexedRoleDS(96): CortexPE\Hierarchy\data\role\IndexedRoleDS->removeRolePermission(object CortexPE\Hierarchy\role\Role, string[20] pocketmine.broadcast)
[19:35:52] [Server thread/DEBUG]: #3 plugins/Hierarchy_v1.2.0.phar/src/CortexPE/Hierarchy/role/Role(164): CortexPE\Hierarchy\data\role\IndexedRoleDS->addRolePermission(object CortexPE\Hierarchy\role\Role, object pocketmine\permission\Permission, boolean 1)
[19:35:52] [Server thread/DEBUG]: #4 plugins/HRKMigrator_dev-3.phar/src/CortexPE/HRKMigrator/Main(245): CortexPE\Hierarchy\role\Role->denyPermission(object pocketmine\permission\Permission)
[19:35:52] [Server thread/DEBUG]: #5 plugins/HRKMigrator_dev-3.phar/src/CortexPE/HRKMigrator/Main(134): CortexPE\HRKMigrator\Main::procRolePermission(object CortexPE\Hierarchy\role\Role, string[20] pocketmine.broadcast)
[19:35:52] [Server thread/DEBUG]: #6 plugins/HRKMigrator_dev-3.phar/src/CortexPE/HRKMigrator/Main(81): CortexPE\HRKMigrator\Main->doMigration()
[19:35:52] [Server thread/DEBUG]: #7 src/pocketmine/scheduler/ClosureTask(61): CortexPE\HRKMigrator\Main->CortexPE\HRKMigrator\{closure}(integer 1)
[19:35:52] [Server thread/DEBUG]: #8 src/pocketmine/scheduler/TaskHandler(134): pocketmine\scheduler\ClosureTask->onRun(integer 1)
[19:35:52] [Server thread/DEBUG]: #9 src/pocketmine/scheduler/TaskScheduler(176): pocketmine\scheduler\TaskHandler->run(integer 1)
[19:35:52] [Server thread/DEBUG]: #10 src/pocketmine/plugin/PluginManager(643): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(integer 1)
[19:35:52] [Server thread/DEBUG]: #11 src/pocketmine/Server(2380): pocketmine\plugin\PluginManager->tickSchedulers(integer 1)
[19:35:52] [Server thread/DEBUG]: #12 src/pocketmine/Server(2143): pocketmine\Server->tick()
[19:35:52] [Server thread/DEBUG]: #13 src/pocketmine/Server(1990): pocketmine\Server->tickProcessor()
[19:35:52] [Server thread/DEBUG]: #14 src/pocketmine/Server(1584): pocketmine\Server->start()
[19:35:52] [Server thread/DEBUG]: #15 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[49] /home/minecraft/multicraft/servers/PE/pocketmine/, string[57] /home/minecraft/multicraft/servers/PE/pocketmine/plugins/)
[19:35:52] [Server thread/DEBUG]: #16 src/pocketmine/PocketMine(296): pocketmine\server()
[19:35:52] [Server thread/DEBUG]: #17 (11): require(string[104] phar:///home/minecraft/multicraft/servers/PE/pocketmine/PocketMine-MP.phar/src/p)

```
Yeah, i know multiworld is not implemented yet, but i don't know, why it is stuck on the 3 Group

```
---
Kinder:
  alias: knd
  inheritance: []
  permissions: []
  worlds:
    Plotwelt:
      isDefault: true
      permissions:
      - essentialstp.command.bedsetshome
      - essentialstp.command.delhome
      - essentialstp.command.home
      - essentialstp.command.sethome
      - essentialstp.command.spawn
      - essentialstp.command.tpa
      - essentialstp.command.tpaccept
      - essentialstp.command.tpahere
      - essentialstp.command.tpdeny
      - essentialstp.command.warp
      - myplot.claimplots.4
      - myplot.command.add
      - myplot.command.auto
      - myplot.command.biome
      - myplot.command.clear
      - myplot.command.denyplayer
      - myplot.command.dispose
      - myplot.command.home
      - myplot.command.info
      - myplot.command.list
      - myplot.command.middle
      - myplot.command.name
      - myplot.command.remove
      - myplot.command.undenyplayer
      - portal.minigames
      - slapper
      - worldguard.enter.Plotwelt
      - worldguard.leave.Plotwelt
    Minigames:
      isDefault: true
      permissions:
      - essentialstp.command.bedsetshome
      - essentialstp.command.delhome
      - essentialstp.command.home
      - essentialstp.command.sethome
      - essentialstp.command.spawn
      - essentialstp.command.tpa
      - essentialstp.command.tpaccept
      - essentialstp.command.tpahere
      - essentialstp.command.tpdeny
      - essentialstp.command.warp
      - portal.plotwelt
      - portal.skyblock
      - portal.skywars
      - slapper
      - worldguard.enter.Minigames
      - worldguard.leave.Minigames
    Projekte:
      permissions: []
    SkyWars:
      isDefault: true
      permissions:
      - portal.swplotwelt
      - slapper
      - sw.cmd.help
      - sw.cmd.join
      - sw.cmd.leave
      - sw.cmd.shop
      - worldguard.enter.Skywars
      - worldguard.leave.Skywars
    SkyBlock:
      isDefault: true
      permissions:
      - essentialstp.command.bedsetshome
      - essentialstp.command.delhome
      - essentialstp.command.home
      - essentialstp.command.sethome
      - essentialstp.command.spawn
      - essentialstp.command.tpa
      - essentialstp.command.tpaccept
      - essentialstp.command.tpahere
      - essentialstp.command.tpdeny
      - essentialstp.command.warp
      - portal.sbplotwelt
      - skyblock.interaction
      - slapper
      - worldguard.enter.Skyblock
      - worldguard.leave.Skyblock
    BedWars:
      isDefault: true
      permissions: []
    Ducktales:
      permissions: []
    SkyLands:
      permissions: []
  isDefault: true
Eltern:
  alias: eln
  inheritance:
  - Kinder
  permissions: []
  worlds:
    Plotwelt:
      isDefault: false
      permissions: []
    SkyBlock:
      isDefault: false
      permissions: []
    Farmwelt:
      isDefault: false
      permissions: []
    Minigames:
      isDefault: false
      permissions: []
    Projekte:
      isDefault: false
      permissions: []
    SkyWars:
      isDefault: false
      permissions: []
    BedWars:
      isDefault: false
      permissions: []
    Ducktales:
      isDefault: false
      permissions: []
    SkyLands:
      isDefault: false
      permissions: []
Architekten:
  alias: atk
  inheritance: []
  permissions:
  - Vanish.see
  - Vanish.use
  - essentials
  - essentials.gamemode
  - essentials.kit
  - essentials.kit.other
  - pchat.colored.format
  - pchat.colored.nametag
  - pocketmine.broadcast
  - pocketmine.command
  - pocketmine.command.gamemode
  - pocketmine.command.give
  - pocketmine.command.kick
  - pocketmine.command.list
  - pocketmine.command.me
  - pocketmine.command.teleport
  - pocketmine.command.time
  - pperms.command
  - pperms.command.ppinfo
  worlds:
    Plotwelt:
      isDefault: false
      permissions:
      - essentialstp.command.back
      - essentialstp.command.bedsetshome
      - essentialstp.command.delhome
      - essentialstp.command.delwarp
      - essentialstp.command.home
      - essentialstp.command.sethome
      - essentialstp.command.setspawn
      - essentialstp.command.setwarp
      - essentialstp.command.sign.spawn
      - essentialstp.command.sign.spawn.break
      - essentialstp.command.sign.spawn.create
      - essentialstp.command.sign.warp
      - essentialstp.command.sign.warp.break
      - essentialstp.command.sign.warp.create
      - essentialstp.command.sign.wild
      - essentialstp.command.sign.wild.break
      - essentialstp.command.sign.wild.create
      - essentialstp.command.spawn
      - essentialstp.command.tpa
      - essentialstp.command.tpaccept
      - essentialstp.command.tpahere
      - essentialstp.command.tpdeny
      - essentialstp.command.warp
      - essentialstp.command.wild
      - invsee.enderinventory
      - invsee.enderinventory.modify
      - invsee.enderinventory.view
      - invsee.inventory
      - invsee.inventory.modify
      - invsee.inventory.view
      - mw.cmd.create
      - mw.cmd.gamerule
      - mw.cmd.help
      - mw.cmd.info
      - mw.cmd.list
      - mw.cmd.load
      - mw.cmd.manage
      - mw.cmd.rename
      - mw.cmd.teleport
      - mw.cmd.unload
      - mw.cmd.update
      - myplot.claimplots.4
      - myplot.command.add
      - myplot.command.auto
      - myplot.command.biome
      - myplot.command.clear
      - myplot.command.denyplayer
      - myplot.command.dispose
      - myplot.command.home
      - myplot.command.info
      - myplot.command.list
      - myplot.command.middle
      - myplot.command.name
      - myplot.command.remove
      - myplot.command.reset
      - myplot.command.undenyplayer
      - pchat.coloredMessages
      - pchat.command
      - pchat.command.setformat
      - pchat.command.setnametag
      - pchat.command.setprefix
      - pchat.command.setsuffix
      - per-world-player.bypass
      - portal.minigames
      - portalspe.admin
      - slapper
      - slapper.command
      - slapper.create
      - slapper.edit
      - slapper.help
      - slapper.id
      - slapper.nothing
      - slapper.rca
      - slapper.remove
      - we.command.brush
      - we.command.copy
      - we.command.debug
      - we.command.flip
      - we.command.flood
      - we.command.paste
      - we.command.pos
      - we.command.redo
      - we.command.replace
      - we.command.rotate
      - we.command.schematic
      - we.command.set
      - we.command.toggledebug
      - we.command.togglewand
      - we.command.undo
      - we.command.wand
      - worldguard.break-bypass.Plotwelt
      - worldguard.build-bypass.Plotwelt
      - worldguard.bypass-cmd.Plotwelt
      - worldguard.create
      - worldguard.delete
      - worldguard.edit.Plotwelt
      - worldguard.enchantingtable.Plotwelt
      - worldguard.enter.Plotwelt
      - worldguard.leave.Plotwelt
      - worldguard.modify
      - worldguard.ui
      - worldguard.useanvil.Plotwelt
      - worldguard.usechest.Plotwelt
      - worldguard.usechestender.Plotwelt
      - worldguard.usecraftingtable.Plotwelt
      - worldguard.usedoors.Plotwelt
      - worldguard.usefurnaces.Plotwelt
      - worldguard.usegates.Plotwelt
      - worldguard.usenoteblock.Plotwelt
      - worldguard.usetrapdoors.Plotwelt
    SkyBlock:
      isDefault: false
      permissions:
      - essentialstp.command.back
      - essentialstp.command.bedsetshome
      - essentialstp.command.delhome
      - essentialstp.command.delwarp
      - essentialstp.command.home
      - essentialstp.command.sethome
      - essentialstp.command.setspawn
      - essentialstp.command.setwarp
      - essentialstp.command.sign.spawn
      - essentialstp.command.sign.spawn.break
      - essentialstp.command.sign.spawn.create
      - essentialstp.command.sign.warp
      - essentialstp.command.sign.warp.break
      - essentialstp.command.sign.warp.create
      - essentialstp.command.sign.wild
      - essentialstp.command.sign.wild.break
      - essentialstp.command.sign.wild.create
      - essentialstp.command.spawn
      - essentialstp.command.tpa
      - essentialstp.command.tpaccept
      - essentialstp.command.tpahere
      - essentialstp.command.tpdeny
      - essentialstp.command.warp
      - essentialstp.command.wild
      - invsee.enderinventory
      - invsee.enderinventory.modify
      - invsee.enderinventory.view
      - invsee.inventory
      - invsee.inventory.modify
      - invsee.inventory.view
      - mw.cmd.create
      - mw.cmd.gamerule
      - mw.cmd.help
      - mw.cmd.info
      - mw.cmd.list
      - mw.cmd.load
      - mw.cmd.manage
      - mw.cmd.rename
      - mw.cmd.teleport
      - mw.cmd.unload
      - mw.cmd.update
      - pchat.coloredMessages
      - pchat.command
      - pchat.command.setformat
      - pchat.command.setnametag
      - pchat.command.setprefix
      - pchat.command.setsuffix
      - per-world-player.bypass
      - portal.sbplotwelt
      - skyblock.interaction
      - slapper
      - slapper.command
      - slapper.create
      - slapper.edit
      - slapper.help
      - slapper.id
      - slapper.nothing
      - slapper.rca
      - slapper.remove
      - we.command.brush
      - we.command.copy
      - we.command.debug
      - we.command.flip
      - we.command.flood
      - we.command.paste
      - we.command.pos
      - we.command.redo
      - we.command.replace
      - we.command.rotate
      - we.command.schematic
      - we.command.set
      - we.command.toggledebug
      - we.command.togglewand
      - we.command.undo
      - we.command.wand
      - worldguard.break-bypass.Skyblock
      - worldguard.build-bypass.Skyblock
      - worldguard.bypass-cmd.Skyblock
      - worldguard.create
      - worldguard.delete
      - worldguard.edit.Skyblock
      - worldguard.enchantingtable.Skyblock
      - worldguard.enter.Skyblock
      - worldguard.leave.Skyblock
      - worldguard.modify
      - worldguard.ui
      - worldguard.useanvil.Skyblock
      - worldguard.usechest.Skyblock
      - worldguard.usechestender.Skyblock
      - worldguard.usecraftingtable.Skyblock
      - worldguard.usedoors.Skyblock
      - worldguard.usefurnaces.Skyblock
      - worldguard.usegates.Skyblock
      - worldguard.usenoteblock.Skyblock
      - worldguard.usetrapdoors.Skyblock
    Minigames:
      isDefault: false
      permissions:
      - essentialstp.command.back
      - essentialstp.command.bedsetshome
      - essentialstp.command.delhome
      - essentialstp.command.delwarp
      - essentialstp.command.home
      - essentialstp.command.sethome
      - essentialstp.command.setspawn
      - essentialstp.command.setwarp
      - essentialstp.command.sign.spawn
      - essentialstp.command.sign.spawn.break
      - essentialstp.command.sign.spawn.create
      - essentialstp.command.sign.warp
      - essentialstp.command.sign.warp.break
      - essentialstp.command.sign.warp.create
      - essentialstp.command.sign.wild
      - essentialstp.command.sign.wild.break
      - essentialstp.command.sign.wild.create
      - essentialstp.command.spawn
      - essentialstp.command.tpa
      - essentialstp.command.tpaccept
      - essentialstp.command.tpahere
      - essentialstp.command.tpdeny
      - essentialstp.command.warp
      - essentialstp.command.wild
      - invsee.enderinventory
      - invsee.enderinventory.modify
      - invsee.enderinventory.view
      - invsee.inventory
      - invsee.inventory.modify
      - invsee.inventory.view
      - mw.cmd.create
      - mw.cmd.gamerule
      - mw.cmd.help
      - mw.cmd.info
      - mw.cmd.list
      - mw.cmd.load
      - mw.cmd.manage
      - mw.cmd.rename
      - mw.cmd.teleport
      - mw.cmd.unload
      - mw.cmd.update
      - pchat.coloredMessages
      - pchat.command
      - pchat.command.setformat
      - pchat.command.setnametag
      - pchat.command.setprefix
      - pchat.command.setsuffix
      - per-world-player.bypass
      - portal.plotwelt
      - portal.skyblock
      - portal.skywars
      - portalspe.admin
      - slapper
      - slapper.command
      - slapper.create
      - slapper.edit
      - slapper.help
      - slapper.id
      - slapper.nothing
      - slapper.rca
      - slapper.remove
      - we.command.brush
      - we.command.copy
      - we.command.debug
      - we.command.flip
      - we.command.flood
      - we.command.paste
      - we.command.pos
      - we.command.redo
      - we.command.replace
      - we.command.rotate
      - we.command.schematic
      - we.command.set
      - we.command.toggledebug
      - we.command.togglewand
      - we.command.undo
      - we.command.wand
      - worldguard.break-bypass.Minigames
      - worldguard.build-bypass.Minigames
      - worldguard.bypass-cmd.Minigames
      - worldguard.create
      - worldguard.delete
      - worldguard.edit.Minigames
      - worldguard.enchantingtable.Minigames
      - worldguard.enter.Minigames
      - worldguard.leave.Minigames
      - worldguard.modify
      - worldguard.ui
      - worldguard.useanvil.Minigames
      - worldguard.usechest.Minigames
      - worldguard.usechestender.Minigames
      - worldguard.usecraftingtable.Minigames
      - worldguard.usedoors.Minigames
      - worldguard.usefurnaces.Minigames
      - worldguard.usegates.Minigames
      - worldguard.usenoteblock.Minigames
      - worldguard.usetrapdoors.Minigames
    Projekte:
      isDefault: false
      permissions:
      - worldguard.create
      - worldguard.modify
      - worldguard.ui
    SkyWars:
      isDefault: false
      permissions:
      - invsee.enderinventory
      - invsee.enderinventory.modify
      - invsee.enderinventory.view
      - invsee.inventory
      - invsee.inventory.modify
      - invsee.inventory.view
      - pchat.coloredMessages
      - pchat.command
      - pchat.command.setformat
      - pchat.command.setnametag
      - pchat.command.setprefix
      - pchat.command.setsuffix
      - per-world-player.bypass
      - portal.swplotwelt
      - sw.cmd.arenas
      - sw.cmd.create
      - sw.cmd.help
      - sw.cmd.join
      - sw.cmd.kick
      - sw.cmd.leave
      - sw.cmd.random
      - sw.cmd.remove
      - sw.cmd.set
      - sw.cmd.shop
      - sw.cmd.start
      - sw.kit
      - worldguard.break-bypass.Skywars
      - worldguard.build-bypass.Skywars
      - worldguard.bypass-cmd.Skywars
      - worldguard.create
      - worldguard.delete
      - worldguard.edit.Skywars
      - worldguard.enchantingtable.Skywars
      - worldguard.enter.Skywars
      - worldguard.leave.Skywars
      - worldguard.modify
      - worldguard.ui
      - worldguard.useanvil.Skywars
      - worldguard.usechest.Skywars
      - worldguard.usechestender.Skywars
      - worldguard.usecraftingtable.Skywars
      - worldguard.usedoors.Skywars
      - worldguard.usefurnaces.Skywars
      - worldguard.usegates.Skywars
      - worldguard.usenoteblock.Skywars
      - worldguard.usetrapdoors.Skywars
    BedWars:
      isDefault: false
      permissions: []
    Ducktales:
      isDefault: false
      permissions: []
    SkyLands:
      isDefault: false
      permissions: []
Team:
  alias: sup
  inheritance:
  - Architekten
  permissions:
  - Vanish.see
  - Vanish.use
  - essentials
  - essentials.gamemode
  - essentials.kit
  - essentials.kit.other
  - pchat.colored.format
  - pchat.colored.nametag
  - pocketmine.broadcast
  - pocketmine.command
  - pocketmine.command.gamemode
  - pocketmine.command.give
  - pocketmine.command.kick
  - pocketmine.command.list
  - pocketmine.command.me
  - pocketmine.command.teleport
  - pocketmine.command.time
  - pperms.command
  - pperms.command.ppinfo
  worlds:
    Plotwelt:
      isDefault: false
      permissions:
      - badwordblocker.bypass
      - badwordblocker.bypass.caps
      - badwordblocker.bypass.same
      - badwordblocker.bypass.spam
      - badwordblocker.bypass.swear
      - pperms.command.addgroup
      - pperms.command.addparent
      - pperms.command.defgroup
      - pperms.command.fperms
      - pperms.command.groups
      - pperms.command.grpinfo
      - pperms.command.listgperms
      - pperms.command.listuperms
      - pperms.command.ppinfo
      - pperms.command.ppreload
      - pperms.command.ppsudo
      - pperms.command.rmgroup
      - pperms.command.rmparent
      - pperms.command.setgperm
      - pperms.command.setgroup
      - pperms.command.setuperm
      - pperms.command.unsetgperm
      - pperms.command.unsetuperm
      - pperms.command.usrinfo
    Minigames:
      isDefault: false
      permissions:
      - badwordblocker.bypass
      - badwordblocker.bypass.caps
      - badwordblocker.bypass.same
      - badwordblocker.bypass.spam
      - badwordblocker.bypass.swear
      - pperms.command.addgroup
      - pperms.command.addparent
      - pperms.command.defgroup
      - pperms.command.fperms
      - pperms.command.groups
      - pperms.command.grpinfo
      - pperms.command.listgperms
      - pperms.command.listuperms
      - pperms.command.ppinfo
      - pperms.command.ppreload
      - pperms.command.ppsudo
      - pperms.command.rmgroup
      - pperms.command.rmparent
      - pperms.command.setgperm
      - pperms.command.setgroup
      - pperms.command.setuperm
      - pperms.command.unsetgperm
      - pperms.command.unsetuperm
      - pperms.command.usrinfo
    Projekte:
      isDefault: false
      permissions: []
    SkyBlock:
      isDefault: false
      permissions:
      - badwordblocker.bypass
      - badwordblocker.bypass.caps
      - badwordblocker.bypass.same
      - badwordblocker.bypass.spam
      - badwordblocker.bypass.swear
    SkyWars:
      isDefault: false
      permissions:
      - badwordblocker.bypass
      - badwordblocker.bypass.caps
      - badwordblocker.bypass.same
      - badwordblocker.bypass.spam
      - badwordblocker.bypass.swear
    BedWars:
      isDefault: false
      permissions: []
    Ducktales:
      isDefault: false
      permissions: []
    SkyLands:
      isDefault: false
      permissions: []
Leitung:
  alias: ltg
  inheritance:
  - Architekten
  - Team
  permissions:
  - Vanish.see
  - Vanish.use
  - essentials
  - essentials.gamemode
  - essentials.kit
  - essentials.kit.other
  - pchat.colored.format
  - pchat.colored.nametag
  - pocketmine.broadcast
  - pocketmine.command
  - pocketmine.command.gamemode
  - pocketmine.command.give
  - pocketmine.command.kick
  - pocketmine.command.list
  - pocketmine.command.me
  - pocketmine.command.teleport
  - pocketmine.command.time
  - pperms.command
  - pperms.command.ppinfo
  worlds:
    Plotwelt:
      isDefault: false
      permissions:
      - devtools
      - devtools.command
      - devtools.command.checkperm
      - devtools.command.checkperm.other
      - devtools.command.extractplugin
      - devtools.command.genplugin
      - devtools.command.makeplugin
      - jhelom.command.wbackup
      - mw.cmd.delete
    Minigames:
      isDefault: false
      permissions:
      - devtools
      - devtools.command
      - devtools.command.checkperm
      - devtools.command.checkperm.other
      - devtools.command.extractplugin
      - devtools.command.genplugin
      - devtools.command.makeplugin
      - jhelom.command.wbackup
      - mw.cmd.delete
    Projekte:
      isDefault: false
      permissions: []
    SkyBlock:
      isDefault: false
      permissions:
      - devtools
      - devtools.command
      - devtools.command.checkperm
      - devtools.command.checkperm.other
      - devtools.command.extractplugin
      - devtools.command.genplugin
      - devtools.command.makeplugin
      - jhelom.command.wbackup
      - mw.cmd.delete
    SkyWars:
      isDefault: false
      permissions:
      - jhelom.command.wbackup
    BedWars:
      isDefault: false
      permissions: []
    Ducktales:
      isDefault: false
      permissions: []
    SkyLands:
      isDefault: false
      permissions: []
Technik:
  alias: tek
  inheritance:
  - Architekten
  - Kinder
  - Leitung
  - Team
  permissions:
  - Vanish.see
  - Vanish.use
  - essentials
  - essentials.gamemode
  - essentials.kit
  - essentials.kit.other
  - pchat.colored.format
  - pchat.colored.nametag
  - pocketmine.broadcast
  - pocketmine.command
  - pocketmine.command.gamemode
  - pocketmine.command.give
  - pocketmine.command.kick
  - pocketmine.command.list
  - pocketmine.command.me
  - pocketmine.command.teleport
  - pocketmine.command.time
  - pperms.command
  - pperms.command.ppinfo
  worlds:
    Plotwelt:
      isDefault: false
      permissions: []
    SkyBlock:
      isDefault: false
      permissions: []
    Minigames:
      isDefault: false
      permissions: []
    Projekte:
      isDefault: false
      permissions: []
    SkyWars:
      isDefault: false
      permissions: []
    BedWars:
      isDefault: false
      permissions: []
    Ducktales:
      isDefault: false
      permissions: []
    SkyLands:
      isDefault: false
      permissions: []
OP:
  alias: op
  isDefault: false
  inheritance:
  - Architekten
  - Kinder
  - Leitung
  - Team
  permissions:
  - '*'
  worlds:
    Plotwelt:
      isDefault: false
      permissions: []
    SkyBlock:
      isDefault: false
      permissions: []
    Minigames:
      isDefault: false
      permissions: []
    Projekte:
      isDefault: false
      permissions: []
    SkyWars:
      isDefault: false
      permissions: []
    BedWars:
      isDefault: false
      permissions: []
    Ducktales:
      isDefault: false
      permissions: []
    SkyLands:
      isDefault: false
      permissions: []
...

```
