### ISSUE TITLE
Permission Bug

### ISSUE THREAD

**Issue by mrpwes** [CortexPE/Hierarchy#39]
Im using [KitUI by Infernus101](https://poggit.pmmp.io/p/KitUI).  |  kit.command **(kit command permission not custom)**, Yes it works fine but the Custom Kit Permission is not working.
When you do Custom Kit Permission permission should be `kit.<kitname>` (default). 
Hrk could not read it 

Startup Hierarchy msg:
```
[Hierarchy] Unknown permission nodes kit.beginner, kit.griefer, kit.shogun on Member(1) role
[Hierarchy] Unknown permission nodes kit.master on VIP(4) role
[Hierarchy] Unknown permission nodes kit.master on Staff(3) role
```
Yes those `kit.beginner, kit.griefer, kit.shogun, kit.master` are my KitUI Custom Permission
<details>
      <summary>My CustomKitUI kit 1example. Yes, I double-check it.</summary>

```yaml
Beginner:

  items:
  - "274:0:1" #StonePickAxe
  - "271:0:1" #Wood Axe
  - "364:0:2" #:Steak
  helmet:
  chestplate:
  leggings:
  boots:

  commands:
 
  cooldown:
    hours: 3
    minutes: 0

  effects:
  
  kit-name: "§0Beginner"

  money: 2
  
  image-url: "----"

  info: "------"
  
  permission: "kit.beginner" #CustomPermission
```
</details>

also, I try to use `/hrk grantperm` but still hrk can't find the **Custom Permission.**
